# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "trusty64"
	config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

	config.vbguest.auto_update = false if config.respond_to?(:vbguest=)

	config.vm.network :private_network, ip: "192.168.77.78"
	#config.vm.network :public_network, bridge: :dummy

	config.vm.synced_folder "../.", "/var/www/pyAPI"

	config.vm.provider :virtualbox do |vb|
		# vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "512", "--cpuexecutioncap", "90", "--name", "pyAPI"]
	end

	config.vm.provision :shell, :path => "bootstrap.sh"
end
